name: GoodServer Deploy

on:
  push:
    branches:
      - master
      - staging
      - next

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.ref, '/master') || !contains(github.event.head_commit.message, '[skip build]') }}
    steps:
      - name: Pre-checks - Env is Dev
        run: |
          echo "HEROKU_APP_NAME=good-server" >> $GITHUB_ENV
          echo "HEROKU_BRANCH=master" >> $GITHUB_ENV

      - name: Pre-checks - Env is QA
        if: ${{ endsWith(github.ref, '/staging') }}
        run: |
          echo "HEROKU_APP_NAME=goodserver-qa" >> $GITHUB_ENV
          echo "HEROKU_BRANCH=staging" >> $GITHUB_ENV

      - name: Pre-checks - Env is PROD
        if: ${{ endsWith(github.ref, '/next') }}
        run: |
          echo "HEROKU_APP_NAME=goodserver-next" >> $GITHUB_ENV
          echo "HEROKU_BRANCH=next" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{env.HEROKU_BRANCH}}

      - run: git pull

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{env.HEROKU_APP_NAME}}
          heroku_email: "alexey@gooddollar.org"